[build]
  publish = "dist"
  command = "npx vite build"

[dev]
  framework = "#static"

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' https: http: data: blob:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https: http:; worker-src 'self' blob:; style-src 'self' 'unsafe-inline' https:; img-src 'self' https: http: data: blob:; font-src 'self' https: data:; connect-src 'self' https: http: wss: ws:; frame-src 'self' https: http:;"

[[redirects]]
  from = "/api/webhook"
  to = "/.netlify/functions/webhook"
  status = 200

[[redirects]]
  from = "/api/create-payment"
  to = "/.netlify/functions/create-payment"
  status = 200

[[redirects]]
  from = "/api/verify-payment"
  to = "/.netlify/functions/verify-payment"
  status = 200

[[redirects]]
  from = "/api/activate-payment"
  to = "/.netlify/functions/activate-payment"
  status = 200

[[redirects]]
  from = "/api/confirm-payment"
  to = "/.netlify/functions/confirm-payment"
  status = 200

[[redirects]]
  from = "/api/ussd-payment-notify"
  to = "/.netlify/functions/ussd-payment-notify"
  status = 200

[[redirects]]
  from = "/api/broadcast-notify"
  to = "/.netlify/functions/broadcast-notify"
  status = 200

[[redirects]]
  from = "/api/withdraw"
  to = "/.netlify/functions/withdraw"
  status = 200

[[redirects]]
  from = "/api/withdraw-hook"
  to = "/.netlify/functions/withdraw-hook"
  status = 200

[[redirects]]
  from = "/api/pv"
  to = "/.netlify/functions/pv"
  status = 200

[[redirects]]
  from = "/api/donations"
  to = "/.netlify/functions/donations"
  status = 200

[[redirects]]
  from = "/api/donations-totals"
  to = "/.netlify/functions/donations-totals"
  status = 200

[[redirects]]
  from = "/api/notify-user"
  to = "/.netlify/functions/notify-user"
  status = 200

[[redirects]]
  from = "/api/send-support-message"
  to = "/.netlify/functions/send-support-message"
  status = 200

[[redirects]]
  from = "/push/onesignal/OneSignalSDKWorker.js"
  to = "/push/onesignal/OneSignalSDKWorker.js"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
