[build]
  publish = "dist"
  command = "npx vite build"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/webhook"
  to = "/.netlify/functions/webhook"
  status = 200

[[redirects]]
  from = "/api/withdraw"
  to = "/.netlify/functions/withdraw"
  status = 200

[[redirects]]
  from = "/api/withdraw-hook"
  to = "/.netlify/functions/withdraw-hook"
  status = 200

[[redirects]]
  from = "/api/pv"
  to = "/.netlify/functions/pv"
  status = 200

[[redirects]]
  from = "/api/donations"
  to = "/.netlify/functions/donations"
  status = 200

[[redirects]]
  from = "/api/donations-totals"
  to = "/.netlify/functions/donations-totals"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
